version: '2'
services:
  redis:
#    build: .
    image: yfix/redis
    restart: always
    volumes:
      - ./docker/redis-data:/data
      - ./docker/var/log/redis:/var/log/redis
      - ./docker/etc/redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
